source "https://rubygems.org"

gem "sinatra"
gem "sinatra-r18n"
gem "sinatra-partial"

gem "pg" 							                  # DB
gem "activerecord", '>= 4.2.0'  	      # ORM
gem 'sinatra-flash' 				            # to enable flash messages
gem 'sinatra-contrib', require: false   # for reloading
gem 'dotenv'                            # environment variables